var NAVTREEINDEX =
{
"index.html":[],
"index.html":[0],
"annotated.html":[1,0],
"class_glowna.html":[1,0,0],
"class_pole__tablicy.html":[1,0,1],
"class_przedmiot.html":[1,0,2],
"classes.html":[1,1],
"functions.html":[1,2,0],
"functions_func.html":[1,2,1],
"functions_vars.html":[1,2,2],
"functions_rela.html":[1,2,3],
"files.html":[2,0],
"main_8cpp.html":[2,0,0],
"p__plecakowy_8cpp.html":[2,0,1],
"p__plecakowy_8hh.html":[2,0,2],
"globals.html":[2,1,0],
"globals_func.html":[2,1,1]
};
